### ISSUE TITLE
msys "sh: cake: command not found"

### ISSUE THREAD

**Issue by dizyart** [AD7six/cakephp-completion#4]
I'm using your fabulous plugin on msysgit bash. 

It works only when I use `Console/cake[TAB]` but when I use just `cake[TAB]` I get this error:

`sh: cake: command not found`

Using cake as an alias in .bashrc

`alias cake='/c/srv/cake/2.3.0/lib/Cake/Console/cake'`

Not sure if this is really an issue or a misconfiguration on my part. Otherwise it works perfectly!

**Comment by AD7six** [comment]
Not sure how, but I've missed this ticket this whole time.

I wouldn't recommend to have `cake` in your path, and instead always point at an explicit executable. Otherwise it's often ambiguous which `cake` you are executing and also conflicts with [coffeescript's make program](http://coffeescript.org/#cake).

So, while I'm not sure how to fix the problem as asked - solution is to not do that :)
